version: '2'

catalog:
  name: nhsuk_content_platform
  version: 1.0.0
  description: |
    NHSUK Content Platform - Wagtail
  minimum_rancher_version: v0.59.0
  questions:
    - variable: "CONTENT_PLATFORM_DOCKER_IMAGE_TAG"
      label: "Content Platform Docker Image Tag"
      required: true
      default: "latest"
      type: "string"
    - variable: "DB_TYPE"
      label: "Database Option"
      required: true
      default: "New SQL Azure"
      type: enum
      options:
        - "New SQL Azure"
        - "Integration SQL Azure Instance"
        - "SQL Local"
        - "SQLITE"
    - variable: "DB_HOST"
      label: "DB Host"
      required: true
      type: "string"
    - variable: "DB_NAME"
      label: "DB Name"
      required: true
      type: "string"
    - variable: "DB_USER"
      label: "DB User"
      required: true
      type: "string"
    - variable: "DB_PASS"
      label: "DB Password"
      required: true
      type: "string"
    - variable: "WAGTAIL_SU_USER"
      label: "Username for Wagtail superuser"
      required: true
      type: "string"
    - variable: "WAGTAIL_SU_PASS"
      label: "Password for Wagtail superuser"
      required: true
      type: "string"
    - variable: "WAGTAIL_SU_EMAIL"
      label: "Email address for Wagtail superuser"
      required: true
      type: "string"
    - variable: "SA_USER"
      label: "DB SA User"
      required: true
      type: "string"
    - variable: "SA_PASS"
      label: "DB SA Password"
      required: true
      type: "string"
    - variable: "DJANGO_SETTINGS_MODULE"
      label: "Django Settings File"
      required: true
      default: "project_settings.settings.production"
      type: "string"
    - variable: "SECRET_KEY"
      label: "Secret Key"
      required: true
      type: "string"
    - variable: "TRAEFIK_DOMAIN"
      label: "Traefik Domain"
      default: "staging.beta.nhschoices.net"
      required: true
      type: "string"

services:
  wagtail:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 5000
      healthy_threshold: 2
      port: 8000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 5000
      strategy: recreate
      request_line: GET "/admin" "HTTP/1.0"
      reinitializing_timeout: 60000
