version: '2'

services:

  web-app-test:
    build:
      context: ${CODE_DIR}/connecting-to-services/
      args:
        NODE_ENV: test
    command: sh -c 'npm run watch-test && npm run git-hook'
    volumes:
      - ${CODE_DIR}/connecting-to-services/:/code
      - app-test-deps:/code/node_modules

  api-test:
    build:
      context: ${CODE_DIR}/nearby-services-api/
      args:
        NODE_ENV: test
    command: sh -c 'npm run watch-test && npm run git-hook'
    environment:
      SNYK_TOKEN: ${SNYK_TOKEN}
    volumes:
      - ${CODE_DIR}/nearby-services-api/:/code
      - api-test-deps:/code/node_modules
    links:
      - mongodb-pharmacy-test:mongo

  mongodb-pharmacy-test:
    build:
      context: ${CODE_DIR}/org-etl/
      dockerfile: Dockerfile-mongodb

volumes:
  app-test-deps:
  api-test-deps:

